# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-18 09:36
from __future__ import unicode_literals

from django.db import migrations, models
import gallery.models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='image',
            field=models.ImageField(height_field='height', upload_to='images/', validators=[gallery.models.image_validation], width_field='width'),
        ),
    ]
