# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-18 10:14
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('gallery', '0002_auto_20170118_1236'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, unique=True),
        ),
        migrations.AlterField(
            model_name='photo',
            name='height',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='photo',
            name='title',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='photo',
            name='width',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
