# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-18 10:16
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0003_auto_20170118_1314'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='author',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
