# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-18 10:54
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import gallery.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('gallery', '0004_auto_20170118_1316'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(blank=True, max_length=50, null=True)),
                ('image_title', models.CharField(max_length=250, null=True)),
                ('image_width', models.IntegerField(default=0, null=True)),
                ('image_height', models.IntegerField(default=0, null=True)),
                ('image', models.ImageField(height_field='image_height', upload_to='images/', validators=[gallery.models.image_validation], width_field='image_width')),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('image_author', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.RemoveField(
            model_name='photo',
            name='author',
        ),
        migrations.DeleteModel(
            name='Photo',
        ),
    ]
