# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-18 11:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import gallery.models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0005_auto_20170118_1354'),
    ]

    operations = [
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250, null=True)),
                ('width', models.IntegerField(default=0, null=True)),
                ('height', models.IntegerField(default=0, null=True)),
                ('image', models.ImageField(height_field='height', upload_to='images/', validators=[gallery.models.image_validation], width_field='width')),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.AlterModelOptions(
            name='profile',
            options={},
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='user_name',
            new_name='city',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='image_author',
            new_name='user',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='image',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='image_height',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='image_title',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='image_width',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='timestamp',
        ),
        migrations.AddField(
            model_name='profile',
            name='country',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='photo',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to='gallery.Profile'),
        ),
    ]
